---
target_model: 'mistralai/Mistral-7B-v0.1'
output: 'Mistral-7B'
tokenizer_name: 'mistralai/Mistral-7B-v0.1'
method: 'zett'
corpus: 'buster'
fine_tuned: false
hypernet: 'https://huggingface.co/benjamin/zett-hypernetwork-Mistral-7B-v0.1'
model_class: 'AutoModelForCausalLM'
vocab_size: 0.75
push_to_hub: false
revision: "refs/pr/95"
